baseURL = "https://enchanting-vacherin-946011.netlify.app/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "AxerZone"
theme = "blowfish"
paginate = 10
enableRobotsTXT = true
summaryLength = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
