# Blowfish Theme Params

colorScheme = "one-light"
defaultAppearance = "light"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = true

# Homepage
[homepage]
  layout = "profile"
  homepageImage = ""
  showRecent = true
  showRecentItems = 8
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = false

# Article
[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = false
  showAuthor = false
  showHero = false
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = true
  showSummary = true
  sharingLinks = false

# List
[list]
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  showSummary = true
  showCards = false
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false

# Taxonomy
[taxonomy]
  showTermCount = true
  showHero = false
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = false

# Sitemap
[sitemap]
  excludedKinds = []

# Header
[header]
  layout = "basic"

# Footer
[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = true
