baseURL: "https://hu-weiming.github.io/"
languageCode: "zh-cn"
title: "Weiming's Blog"
theme: "PaperMod"
paginate: 10

params:
  env: production
  defaultTheme: auto
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  TocOpen: false

  homeInfoParams:
    Title: "Hey 👋"
    Content: "Java 开发 / 大模型爱好者 / 在读大三学生"

  socialIcons:
    - name: github
      url: "https://github.com/Hu-Weiming"

  label:
    text: "Weiming's Blog"

menu:
  main:
    - identifier: archives
      name: 归档
      url: /archives/
      weight: 10
    - identifier: categories
      name: 分类
      url: /categories/
      weight: 20
    - identifier: tags
      name: 标签
      url: /tags/
      weight: 30
    - identifier: about
      name: 关于
      url: /about/
      weight: 40

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: false
    style: monokai
