backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"
site_url: "https://enchanting-vacherin-946011.netlify.app"
display_url: "https://enchanting-vacherin-946011.netlify.app"
locale: "zh_Hans"

collections:
  - name: "posts"
    label: "文章"
    label_singular: "文章"
    folder: "content/posts"
    create: true
    delete: true
    extension: "md"
    format: "frontmatter"
    slug: "{{slug}}"
    preview_path: "posts/{{slug}}/"
    identifier_field: "title"
    summary: "{{title}}"
    sortable_fields: ["date", "title", "draft"]
    fields:
      - label: "标题"
        name: "title"
        widget: "string"
      - label: "发布日期"
        name: "date"
        widget: "datetime"
        default: "{{now}}"
      - label: "摘要"
        name: "description"
        widget: "text"
        required: false
      - label: "分类"
        name: "categories"
        widget: "list"
        required: false
        allow_add: true
        field:
          label: "分类名"
          name: "category"
          widget: "string"
      - label: "标签"
        name: "tags"
        widget: "list"
        required: false
        allow_add: true
        field:
          label: "标签名"
          name: "tag"
          widget: "string"
      - label: "草稿"
        name: "draft"
        widget: "boolean"
        default: false
      - label: "正文"
        name: "body"
        widget: "markdown"

  - name: "pages"
    label: "页面"
    files:
      - label: "首页"
        name: "home"
        file: "content/_index.md"
        fields:
          - label: "标题"
            name: "title"
            widget: "string"
          - label: "摘要"
            name: "description"
            widget: "text"
            required: false
          - label: "正文"
            name: "body"
            widget: "markdown"
      - label: "关于"
        name: "about"
        file: "content/about/index.md"
        fields:
          - label: "标题"
            name: "title"
            widget: "string"
          - label: "摘要"
            name: "description"
            widget: "text"
            required: false
          - label: "正文"
            name: "body"
            widget: "markdown"
